FROM python:latest
LABEL authors="erkin"
ENV PYTHONWRITEBYTECODE 1
ENV PYTHONBUFFERED 1
WORKDIR /shop_api

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r /shop_api/requirements.txt
ADD . .
